# Generated by Django 5.0 on 2024-01-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lutador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('genero', models.TextField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField(help_text='Formato: (XX)XXXXX-XXXX', max_length=14)),
                ('endereco', models.TextField(help_text='Formato: Rua, Número, Bairro', max_length=255)),
                ('graduacao', models.TextField(max_length=50)),
                ('faixa', models.TextField(max_length=20)),
                ('categoria', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'lutadores_table',
            },
        ),
        migrations.CreateModel(
            name='Mestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('genero', models.TextField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.TextField(help_text='Formato: (XX)XXXXX-XXXX', max_length=14)),
                ('endereco', models.TextField(help_text='Formato: Rua, Número, Bairro', max_length=255)),
                ('graduacao', models.TextField(max_length=50)),
                ('faixa', models.TextField(max_length=20)),
                ('categoria', models.TextField(max_length=50)),
                ('certificado', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'mestres_table',
            },
        ),
    ]
