# Generated by Django 5.0 on 2024-01-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste_BD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutador',
            name='senha',
            field=models.TextField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='mestre',
            name='senha',
            field=models.TextField(default='0', max_length=255),
        ),
    ]
