# Generated by Django 5.0 on 2024-01-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste_BD', '0002_lutador_senha_mestre_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutador',
            name='telefone',
            field=models.IntegerField(help_text='Formato: (XX)XXXXX-XXXX', max_length=14),
        ),
        migrations.AlterField(
            model_name='mestre',
            name='telefone',
            field=models.IntegerField(help_text='Formato: (XX)XXXXX-XXXX', max_length=14),
        ),
    ]
