# Generated by Django 5.0.1 on 2024-01-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste_BD', '0005_alter_lutador_telefone_alter_mestre_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lutador',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='mestre',
            name='senha',
        ),
    ]
