# Generated by Django 5.0.1 on 2024-01-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste_BD', '0006_remove_lutador_senha_remove_mestre_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lutador',
            name='telefone',
            field=models.IntegerField(help_text='Exemplo: (XX)XXXXX-XXXX / Apenas números'),
        ),
        migrations.AlterField(
            model_name='mestre',
            name='telefone',
            field=models.IntegerField(help_text='Exemplo: (XX)XXXXX-XXXX / Apenas números'),
        ),
    ]
