# Generated by Django 5.0.1 on 2024-01-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_teste_BD', '0007_alter_lutador_telefone_alter_mestre_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaveamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lutador_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutador_1', to='app_teste_BD.lutador')),
                ('lutador_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lutador_2', to='app_teste_BD.lutador')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vencedor', to='app_teste_BD.lutador')),
            ],
            options={
                'db_table': 'chaveamento',
            },
        ),
    ]
